### ISSUE TITLE
Auto Make Commands

### ISSUE THREAD

**Issue by eorroe** [twolfson/sublime-edit-command-palette#4]
I like what this plugin solves, would it be possible:

To look through all key bindings and if they don't have a command palette command implemented simply do:

`this_is_an_example_command`:

Then the Command Palette will have:

```
This Is An Example Command
```

So it'd be:

```
[
  {
    "caption": "This Is An Example Command",
    "command": "this_is_an_example_command"
  }
]
```

So simply split up the command and with spaces and capitalize the letter

**But don't put these in the files they are just done automatically, and then people can easily replace them as well with how the package allows now**

**Comment by twolfson** [comment]
That's an interesting idea but I think it's outside of the scope of this project. That being said, if you are interested in building the plugin, then you should be able to reuse code from the following:
- Can reuse keyboard shortcut listings here:
  - https://github.com/MiroHibler/sublime-keymaps
- Use a "save" hook to detect whenever a new plugin save occurs (not sure if there are any better hooks in Package Control for when a new plugin is installed)
  - http://www.sublimetext.com/docs/3/api_reference.html#sublime_plugin.EventListener
  - On this occurrence, we should be able to update a `.sublime-commands` file in the plugin

**Comment by eorroe** [comment]
If I ever do it'll probably be no time soon, but why is this outside the scope of the project?

**Comment by twolfson** [comment]
This project focuses on doing one thing well which is providing the ability to add new commands to the command palette. Adding on specific features like scraping keybindings and listening for plugin edits is outside of that goal and leads to undesirable focus/maintenance work

**Comment by eorroe** [comment]
You might be able to use [this plugin](https://github.com/MiroHibler/sublime-keymaps/blob/master/Keymaps.py)'s algorithm to scrape the keymaps

If that helps, and yes Ik your busy, and I honestly don't even mind waiting a year, so take your time, but please let me know when that happens

**Comment by eorroe** [comment]
Related to this, if a `caption` is not provided, and only the `command` could the plugin just do the command spliting `fake_command` -> caption automatically set to `Fake Command`
